version: '3.3'

services:
  app:
    build:
      context: .
    volumes:
      - "./app:/app"
    ports:
      - "8000:8000"
    entrypoint: "/app/start.sh"
    extra_hosts:
      - "host.docker.internal:host-gateway"
